openapi: 3.0.3
info:
  title: WarmHouse - Scenarios Service API
  version: 0.1.0
  description: API сервиса сценариев. Управление сценариями, шагами и расписанием, запуск сценариев
servers:
  - url: https://api.example.com/scenarios
paths:
  /scenarios:
    get:
      summary: Список сценариев
      operationId: listScenarios
      parameters:
        - in: query
          name: householdId
          schema:
            type: string
            format: uuid
        - in: query
          name: ownerUserId
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Scenario'
    post:
      summary: Создать сценарий
      operationId: createScenario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ScenarioCreateRequest'
      responses:
        '201':
          description: Создано
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Scenario'
  /scenarios/{scenarioId}:
    get:
      summary: Получить сценарий
      operationId: getScenario
      parameters:
        - in: path
          name: scenarioId
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Scenario'
    patch:
      summary: Обновить сценарий
      operationId: updateScenario
      parameters:
        - in: path
          name: scenarioId
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ScenarioUpdateRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Scenario'
    delete:
      summary: Удалить сценарий
      operationId: deleteScenario
      parameters:
        - in: path
          name: scenarioId
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Удалено
  /scenarios/{scenarioId}/run:
    post:
      summary: Запустить сценарий
      operationId: runScenario
      parameters:
        - in: path
          name: scenarioId
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '202':
          description: Принято к выполнению
  /scenarios/{scenarioId}/steps:
    put:
      summary: Заменить шаги сценария
      operationId: replaceScenarioSteps
      parameters:
        - in: path
          name: scenarioId
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/ScenarioStep'
      responses:
        '200':
          description: OK
  /scenarios/{scenarioId}/schedules:
    put:
      summary: Задать расписание сценария
      operationId: setScenarioSchedules
      parameters:
        - in: path
          name: scenarioId
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/ScenarioSchedule'
      responses:
        '200':
          description: OK
components:
  schemas:
    Scenario:
      type: object
      required: [id, name, enabled, householdId]
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        enabled:
          type: boolean
        householdId:
          type: string
          format: uuid
        ownerUserId:
          type: string
          format: uuid
          nullable: true
        createdAt:
          type: string
          format: date-time
        steps:
          type: array
          items:
            $ref: '#/components/schemas/ScenarioStep'
        schedules:
          type: array
          items:
            $ref: '#/components/schemas/ScenarioSchedule'
    ScenarioCreateRequest:
      type: object
      required: [name, enabled, householdId]
      properties:
        name:
          type: string
        enabled:
          type: boolean
        householdId:
          type: string
          format: uuid
        ownerUserId:
          type: string
          format: uuid
          nullable: true
    ScenarioUpdateRequest:
      type: object
      properties:
        name:
          type: string
        enabled:
          type: boolean
        ownerUserId:
          type: string
          format: uuid
          nullable: true
    ScenarioStep:
      type: object
      required: [order, action]
      properties:
        order:
          type: integer
          minimum: 0
        action:
          type: string
          description: command | wait | condition
        params:
          type: object
          additionalProperties: true
    ScenarioSchedule:
      type: object
      required: [cronExpression, timezone, enabled]
      properties:
        cronExpression:
          type: string
        timezone:
          type: string
        enabled:
          type: boolean


