@startuml
title Warmhouse Container Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Person(user, "User", "A user of Warmhouse system")

System_Ext(Browser, "Browser", "External Browser for communication with Warmhouse system")
System_Ext(Ivideon, "Ivideon", "External Syystem for CCTV services")

System(SBSystem, "SmartBuilding System", "System providing set of functions for houses smartisation both private and communal")

Container_Boundary(SBSystem, "SmartBuilding System") {
  Container(SBS, "Smart_home monolith", "Java", "Processes Temperature data")
  Container(TempAPI, "Temperature-api", "Java", "Processes Temperature data")
  Container(SCUD, "SCUD system", "Java", "Processes Temperature data")
  Container(LCS, "Light control", "Java", "Processes Temperature data")
  }

System_Ext(api, "Device API", "External API for communication with Devices")

Rel(user, Browser, "Uses the system")

Rel(Browser, TempAPI, "Uses the system")
Rel(Browser, SCUD, "Uses the system")
Rel(Browser, LCS, "Uses the system")
Rel(Browser, Ivideon, "Uses the system")

Rel(SBS, api, "")
Rel(TempAPI, api, "")
Rel(TempAPI, SBS, "")
Rel(SCUD, api, "")
Rel(LCS, api, "")

@enduml