@startuml
title Warmhouse Context Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Person(user, "User", "A user of Warmhouse system")
System(WHS, "Warmhouse System", "System managing temperature, showing temperature set")

System_Ext(api, "Device API", "External API for communication with Devices")
System_Ext(Browser, "Browser", "External Browser for communication with Warmhouse system")

Rel(user, Browser, "Uses the system to manage temperature in a house")
Rel(WHS,api,"Fetches Value data")
Rel(Browser, WHS, "Communicates to the system")

@enduml