### Проверим что temperature-api возвращает температуру
GET http://localhost:8081/temperature?location=test 

### Проверим что temperature-api зарегистрировалось в gateway
GET http://localhost:8083/api/v1/modules

### Получим температуру из temperature-api через gateway
GET http://localhost:8083/api/v1/modules/temperature-module-factory-001/proxy/temperature?location=kitchen

### Получим температуру из "монолита" smart_home
GET http://localhost:8080/api/v1/sensors/temperature/kitchen 

### Получение состояния отопления из микросервиса отопления (heat service)
GET http://localhost:8082/api/v1/heat/state/temperature-module-factory-001

### Установка нового режима отопления через микросервис отопления (heat service)
POST http://localhost:8082/api/v1/heat/commands/mode?deviceId=temperature-module-factory-001&mode=MANUAL

### Установка целевой температуры
POST http://localhost:8082/api/v1/heat/commands/temperature?deviceId=temperature-module-factory-001&temperature=18.0