@startuml warmhouse heat class diagram

title Система "Тёплый Дом" — Диаграмма классов: Сервис отопления

skinparam classAttributeIconSize 0

package "api" {

    class CommandsController {

    }

    class LoadDataController {

    }

}

package "service" {

    class CommandService {

    }

    class LoadDataService {

    }

    class TelemetryService {

    }

}

package "integration" {

    class ModuleAdapter {

    }

    class EventProducer {

    }

    class TelemetryConsumer {

    }

}

package "db" {

    interface HeatConfigurationRepository {

    }

    interface TelemetryRepository {

    }

}

CommandsController -down-> CommandService
LoadDataController -down-> LoadDataService

TelemetryService -down-> TelemetryRepository
LoadDataService -down-> TelemetryRepository
CommandService -down-> HeatConfigurationRepository

LoadDataService --> ModuleAdapter
CommandService --> ModuleAdapter 
CommandService --> EventProducer 
TelemetryService --> EventProducer 
TelemetryConsumer --> TelemetryService


@enduml


