@startuml warmhouse containers diagram
!include ../assets/C4_templates/C4_Container.puml

title Система "Тёплый Дом" TO BE (C4 Containers)

Person_Ext(user, "Пользователь", "")

Boundary(home, "Домохозяйство", "содержит один или несколько модулей") {
    Container(heat, "ПАК Модуль отопления", "Java, REST API", "Предоставляет данные отопления и механизмы управления им")
    Container(locks, "ПАК Модуль дверей", "Java, REST API", "Предоставляет данные отопления и механизмы управления им")
    Container(surveillance, "ПАК Модуль видеонаблюдения", "Java, REST API", "Предоставляет данные отопления и механизмы управления им")
    Container(light, "ПАК Модуль освещения", "Java, REST API", "Предоставляет данные отопления и механизмы управления им")
}

Enterprise_Boundary(enterprise, "Тёплый Дом") {
    Container(gateway, "Gateway для модулей", "Java, Spring", "Регистрация и авторизация модулей, маршрутизация запросов, телеметрия и аудит")
    Container(user_gui, "UI управления умным домом" , "PWA, React")

    Container(scenarios, "Сервис сценариев", "Java, Spring", "Управляет (запускает, проверяет, хранит) пользовательскими и предустановленными сценариями")
    Container(bff, "Backend For Frontend", "Java, Spring", "Gateway для frontend'а, управляет авторизацией, маршрутизацией и и.п.")

    Container(auth, "User service", "Java, Spring", "Аутентификация. авторизация и каталог пользователей")

    Boundary(modules, "Сервисы модулей") {
        Container(heat_be, "Сервис отопления", "Java, Spring", "")
        Container(locks_be, "Сервис дверей", "Java, Spring", "")
        Container(surveillance_be, "Сервис видеонаблюдения", "Java, Spring", "")
        Container(light_be, "Сервис освещения", "Java, Spring", "")
    }

    ContainerQueue(eventq, "Очередь событий")

}

Rel_D(heat, gateway, "")
Rel_D(surveillance, gateway, "")
Rel_D(light, gateway, "")
Rel_D(locks, gateway, "")
Rel(gateway, auth, "")

Rel_U(modules, gateway, "")
Rel(modules, eventq, "")
Rel(scenarios, eventq, "")
Rel(scenarios, modules, "")
Rel(bff, scenarios, "")
Rel(bff, auth, "")

Rel(user, user_gui, "")
Rel(user_gui, bff, "")
Rel(bff, modules, "")


@enduml
